---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2021-06-24T18:18:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kubectl-create
    operation: Update
    time: "2021-06-24T18:18:35Z"
  name: data-engineering
  resourceVersion: "115967374"
  uid: 32d0dd4b-a671-41b1-babc-f6a2440c300a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
