apiVersion: v1beta
kind: Secret
metadata:
  name: secrets.yaml
data:
  env_vars:
  - username: SECRET_ONE
    password: "This is the value of SECRET_ONE"
  - username: SECRET_TWO
    password: "This is the value of SECRET_TWO"
