name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./dataengctl
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.17

    - name: Tidy
      run: go mod tidy
      working-directory: ${{ env.working-directory }}
      
    - name: Test
      run: go test -v ./...
      working-directory: ${{ env.working-directory }}
      
    - name: Build
      run: go build -v ./...
      working-directory: ${{ env.working-directory }}
