name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating an issue with the repository. We will try to resolve this issue as quickly as possible.'
        pr-message: 'Thank you for creating a pull request with dataeng, a core reviewer will review the changes shortly.'
